Footer import error fixed
JoshuaKGoldberg/next-js-to-ts pull request #3
Opened 2022-04-05 09:54 UTC by sayinmehmet47

2022-04-05 19:57 UTC, JoshuaKGoldberg commented
Hey @sayinmehmet47, what error are you trying to fix here? The code seems to run fine for me, and I prefer named exports over defaults...?

2022-04-05 20:26 UTC, sayinmehmet47 commented
@JoshuaKGoldberg I cloned the repo, and when I do 

``` js
npm install
``
the project can not start because of the some errrors I fixed. In your youtube tutorial it start directly after install dependencies. But in my machine it fired this small errors. I wanted to fix them.

2022-04-05 20:52 UTC, JoshuaKGoldberg commented
Ah, got, thanks! The default settings somewhere must have changed - this used to work out of the box 😄.

The issue isn't with using a default export or not; it's with case sensitivity. https://github.com/JoshuaKGoldberg/next-js-to-ts/blob/2a03187fa98abca404468ead7c8519eabb01d884/src/components/Layout.js#L3

The file name is `Footer.js`, not `footer.js`.

2022-04-05 20:53 UTC, JoshuaKGoldberg requested changes
The only change you should need to make is in `src/components/Layout.js`, switching the lower-case `f` in `"./footer;"` to `F`.

Thanks for sending this in!

2022-04-05 20:56 UTC, sayinmehmet47 commented
@JoshuaKGoldberg  anyway thank you so much also for tutorial:) It helps me a lot to implement typescript in my project

2022-04-05 21:35 UTC, JoshuaKGoldberg commented on src/components/Footer.js
> +export default function Footer() {
There's no need to change this.

```suggestion
export function Footer() {
```

2022-04-05 21:35 UTC, JoshuaKGoldberg requested changes

2022-04-05 21:35 UTC, JoshuaKGoldberg commented on src/components/Footer.test.js
> -});
😢 but I like these tests!

2022-04-06 14:06 UTC, JoshuaKGoldberg commented on src/components/Footer.test.js
> -import { Footer } from "./Footer";
There shouldn't be any changes to this file. The import here was correct before.

* `import Footer from "./Footer";` is a _default_ import. It retrieves the object under the name `default` from `"./Footer"`, and stores it in a variable named `Footer`.
* `import { Footer } from "./Footer";` is a _named_ import. It retrieves the object under the name `Footer` from `"./Footer"`, and stores it in a variable named `Footer`.

https://stackoverflow.com/questions/46913851/why-and-when-to-use-default-export-over-named-exports-in-es6-modules

2022-04-06 14:07 UTC, JoshuaKGoldberg requested changes
Closer!

2022-04-06 14:07 UTC, JoshuaKGoldberg commented on src/components/Layout.js
> -import { Footer } from "./footer";
Same here: the issue was casing, not switching from named to default.

2022-04-06 14:07 UTC, JoshuaKGoldberg commented on src/components/Layout.js
> +    <Footer/>
Please revert this line's change. It was nicely formatted before. 🙂

2022-06-23 16:38 UTC, JoshuaKGoldberg commented on src/components/Footer.test.js
```suggestion

import { Footer } from "./Footer";
```

2022-06-23 16:39 UTC, JoshuaKGoldberg approved these changes
Thanks for this fix @sayinmehmet47! And sorry for taking so long to merge - I was waiting for one last fix to another file, but it was small and I just did it myself.

We should note that the workshop was structured to intentionally show that this file casing is something caught by TypeScript. Since it seems to not work out of the box on Linux/Mac, we'll just have to go without that finding. Ah well. 🙂

2022-06-23 16:40 UTC, merged

2022-06-24 08:56 UTC, sayinmehmet47 commented
@JoshuaKGoldberg  Thanks for merging it , it takes long time but thanks for merging it